apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapi
spec:
  selector:
    matchLabels:
      app: todoapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todoapi
    spec:
      containers:
        - name: restapi
          image: sthinbetween/todoapi
          ports:
          - name: http
            protocol: TCP
            containerPort: 8080
            hostPort: 8080
