apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapi
  labels:
    run: todoapi
spec:
  replicas: 3
  selector:
    matchLabels:
      run: todoapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: todoapi
    spec:
      containers:
        - name: todoapi
          image: sthinbetween/todoapi
          ports:
          - containerPort: 8080
          imagePullPolicy: Always
          env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mariadb://maria-db:3306/restDB"
---
apiVersion: v1
kind: Service
metadata:
    name: todo-service
spec:
    selector:
      run: todoapi
    ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: todo-ingress
    annotations:
        kubernetes.io/ingress.class: haproxy
spec:
    rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: todo-service
              port:
                number: 8080
